stages:
  - build

# cache:
#   paths:
#     - ci_tools/
#     - vendor/
#     - .koderover/

variables:
  CI_LANGUAGE: go
  CI_FOLDER: pkg


test:
  stage: build
  image: maven:3.6.2-jdk-11
  script:
    - mvn package
    - ls ~/.m2/
    